### ISSUE TITLE
Are community contributions are welcomed? (includes list of possible enhancements)

### ISSUE THREAD

**Issue by tscholze** [microsoft/surface-duo-sdk-xamarin-samples#1]
Hi team,
Are community contributions to this repository is welcomed? Or will the source change dramatically in the near future?

**Ideas**
I have the following enhancements in mind:

- Unify code formatting 
   - Removing unused imports
   - Removing duplicated line spaces
   - This would help to „read“ the lib classes
- Add documentation to the Surface Duo related library classes like `TwoPaneView`, both of the services, etc.
    - E.g what does the height or witch configuration enum values mean in detail (which value is related to which pane configuration?)
    - Add relationship diagram how the lib classes works together
    - DuoPage has FormsWindow which contains the LayoutService that relies on a working dependency injected member 
- Add „how to get started“ section which classes you have to use for your own project
    - Platform specific dependency classes and unit of them (`MainActivity.cs` changes)
- Improve services to work in other apps
    - E.g. Make `isDuo` property public accessible

**Contact**
If anyone wants to chat wit me about this topic, tweet me @tobonaut on Twitter. :)

**Comment by conceptdev** [comment]
Both Xamarin.Forms, and the documentation, are open source! You can check out the repos and contribution guidelines for each of them:

* https://github.com/xamarin/Xamarin.Forms
* https://github.com/MicrosoftDocs/xamarin-docs

In general, contributions always start with an issue that contains either a bug, or a proposal. Once the team is engaged and understands the issue and agrees on a way forward, work can start on a PR.

While everything is still in preview, there is still a chance that things change, so that will factor into our plans.

My suggestion would be start small, and create an issue (like you have done here), but for a specific achievable goal, get some feedback from the team, and take it from there. There is a lot of community contribution already happening in the Xamarin.Forms codebase, so that's a great place to read old issues and get a feeling for how things are done. And of course, if you ever have any questions, just ask.
