### ISSUE TITLE
Can't select Surface Duo emulator in Visual Studio for Mac.

### ISSUE THREAD

**Issue by owlstack** [microsoft/surface-duo-sdk-xamarin-samples#3]
Hi, 

I'm trying to run the Xamarin.Forms sample on my Android Surface Duo emulator running in the background. When I go to make the selection for the emulator, after I select it, it default back to the other AVD device I have saved instead. It doesn't like it when I select the emulator. I haven't tested it where if I delete the other AVD, if it just default onto itself but this is a bug. 

EDIT: After exiting VS and playing around with the selector, I got it to correctly default to the right one and it works. Idk if this still considered a bug worth an investigation into or not however? Looks like maybe that happens on first time trying to default to the emulator?

**Comment by conceptdev** [comment]
Hey @owlstack, thanks for the feedback (and sorry for the delay in response). The current preview of the Surface Duo emulator will not automatically appear in the emulator list inside Visual Studio.

However, once you start the emulator directly, it will appear in Visual Studio as a target for deployment. 

I'm not sure that also explains the weird behavior you saw (when you select it and defaults back to a different AVD), but since we have new releases of the emulator and Visual Studio since you posted, perhaps this is now resolved 🤞 let us know if you continue to have issues.
