### ISSUE TITLE
[Feature request] Introduce helper to determine if an Xamarin.Forms app runs on a Duo device

### ISSUE THREAD

**Issue by tscholze** [microsoft/surface-duo-sdk-xamarin-samples#4]
**Idea**

The large screens of the Duo are able to present more information than any other "single" screen Android device.
That's why I need to know if the app is running on a Surface Duo or not. In my optionen, please correct me if this feature already exists, a simple member provided by the SDK that indicatates if it is running on a Duo would be great.

**Example extension**

```
public static class DualScreenInfoExtensions
{
    public static bool IsDuo(this DualScreenInfo dualScreenInfo)
    {
        return DualScreenInfo.Current.HingeBounds.Width != 0;
     }
}
 
```

**Example usage**

For example to show a multi column layout for "is a Duo" and a single column layout for "is not a Duo"

```
if(DualScreenInfo.Current.IsDuo())
{
    SecondColumnWidth = new GridLength(1, GridUnitType.Star);
}
else
{
    SecondColumnWidth = new GridLength(0, GridUnitType.Absolute);
}
```

**TechCommunity**
[I also opened a post](https://techcommunity.microsoft.com/t5/surface-duo-sdk/feature-request-introduce-helper-to-determine-if-an-xamarin/m-p/1220648#M57) in the official Surface Duo SDK TechCommunity forum.

**Comment by conceptdev** [comment]
Thanks for the feedback @tscholze. There's two answers :)

[You can check](https://docs.microsoft.com/en-us/dual-screen/android/sample-code/is-dual-screen-device) with `hasSystemFeature`, even without any of our SDKs installed:

```java
private boolean isDualScreenDevice(){
        String feature = "com.microsoft.device.display.displaymask";
        PackageManager pm = this.getPackageManager();

    if (pm.hasSystemFeature(feature)) {
        Log.i(TAG, "System has feature: " + feature);
        return true;
    } else {
        Log.w(TAG, "System missing feature: " + feature);
        return false;
    }
}
```

Since you posted, we have also released a new package that includes a `ScreenHelper` class, with some methods you can use to query the screens and whether the app is spanned across them. See [the ScreenHelper documentation](https://docs.microsoft.com/dual-screen/android/api-reference/dualscreen-layout) for more info

Hope that helps!
